[package]
name = "libfri"
version = "0.1.0"
edition = "2021"
authors = [ "Pawel pgmerek@proton.me"]

[dependencies]
rans = "0.2.1"
num = "0.4.3"
itertools = "0.14.0"
nalgebra = "0.33.0"
lstsq = "0.6.0"
